apiVersion: v1
kind: Pod
metadata:
  name: app1-pod
spec:
  containers:
    - name: primer-pod
      image: pod1-image:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
      command: ["node"]
      args: ["index.js"]
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
        requests:
          cpu: "0.5"
          memory: "256Mi"

